
<div class="picture">
  <img src="pix/me-as-a-simpson.jpg" alt='Marcin as a Simpsons character' 
  title="Regrettably, this is my actual skin color." /><br />
</div>
<!--  title="Not unprofessional because books."  -->

%  <em>I&rsquo;m told people like it when you have a picture of yourself on your website.</em>

%Here's the basic information: %
%  |what I work on:|
%    semantics and the syntax-semantics interface 
%      %(which is part of theoretical linguistics)
%      %(for elaboration, look at [this](interests/))
%
%  |job:|
   % associate professor of linguistics  
   % [Dept. of Linguistics and Languages][dept]  

%These are some things that are true of me:
%
%  • I am a theoretical linguist with a primary interest in semantics and the syntax-semantics interface.
%  • I am an associate professor of linguistics in the [Dept. of Linguistics and Languages][dept] at Michigan State University.
%  • You can email me at <span id="email">my last name at msu.edu</span>.
%  • My office hours for Spring '10 are Tuesday 4:30-5:30 and Thursday 2:00--3:00. My office is A-634 Wells Hall.

Hi. Here's a short FAQ: 

  |Who are you?| 
    I'm an associate professor of linguistics at the 
    [University of British Columbia][dept] working on semantics and the syntax-semantics interface.

  |How can I contact you?|
      [marcin.morzycki@ubc.ca][email]

  |How can I talk to you directly?|
    If you're in a class I'm teaching, my current office hours are on the 
    Canvas site and and on the syllabus. If you're not, don't hesitate to 
    [email me][email] to set up a Zoom appointment or an in-person one
    % I'm not teaching at the moment, so my office hours are by appointment.
    % My office hours during term 2 are Mondays 2:30--3:30 
    at [Totem Fields Studios][TFSmap] 226.
    % or by appointment.

  |How do I pronounce your name?|
    In [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet), it's <span 
    class="IPA">[ˈmɑɹsɪnmɔɹˈzɪki]</span>. This is Anglicized Polish. 
      %It's Polish. (My name, not your browser.) 
    People who know anything about Polish understandably find it appalling. The
    non-Anglicized version is <span class="IPA">[ˈmart͡ɕinmɔˈʐɨt͡ski]</span>,
    but only Polish speakers call me that. (If you can't read IPA, you should
    take a linguistics course. If you just see a series of boxes due to font
    problems, don't assume my name is pronounced as a series of boxes.) 
    % There is another Polish semanticist, Marcin Wągiel, who pronounces his 
    % first name correctly.

[dept]: http://linguistics.ubc.ca
[TFSmap]: https://www.google.com/maps/place/2613+West+Mall,+Vancouver,+BC+V6T+1Z2
%https://www.google.com/maps/place/UBC+Department+of+Linguistics/@49.2561087,-123.2511914,17z/data=!3m1!4b1!4m5!3m4!1s0x548672c96fd324f1:0x219a38a2bc45e747!8m2!3d49.2561087!4d-123.2489974
%/@49.2561161,-123.2511899,17z/data=!3m1!4b1!4m5!3m4!1s0x548672ccdf1747cb:0xf1fa5e15112b549!8m2!3d49.2561161!4d-123.2489959
[email]: mailto:ma%72ci%6e&#046;&#109;%6f&#114;z%79&#099;k&#105;&#064;&#117;%62c.&#099;&#097;

% If you're wondering how to pronounce my name, can read
% [IPA](http://www.langsci.ucl.ac.uk/ipa), and have a browser that displays it
% properly, it's <span class="IPA">[ˈmɑɹsɪnmɔɹˈzɪki]</span>. This is Anglicized
% Polish.
%% It's Polish. (My name, not your browser.) If you know anything at all about
%% Polish you will be horrified and offended by this pronunciation. In actual
%% Polish, it would be []. I was imported into the US at age six. This is not
%% an age at which it's easy to persuade people to pronounce Polish names in
%% Polish, so it got Anglicized pretty fast.

%I used to have a page of links and linguistics resources, but that seems somehow retrograde these days---one just doesn't _do_ that anymore, though I'm not entirely sure why. Nevertheless, here are a few remnants of it: this essay by the philosopher John Perry on '[structured procrastination][procrastination]' that I think may be deeply wise and this now out-of-date but still potentially useful starting point for doing [linguistics using LaTeX][LaTeX_Penn].

%: ADD?:
%: 
%:   • intellectual biography of some kind, including mention of Angelika,
%:     Sandy, etc
%:   • deal on my name, w/ ipa pronunciation and Polish story?
%:   • 'welcome' or some such?
%:   • more explicit contact info, w/ 'by email', 'by snail mail', etc?
%:   • conceivably some separate 'about me' thing? with lies and truth
%:     intermingled? 'briefly served as the first female pope' etc., end with
%:     'some of this was true'
%:   • add 'known allergies' or 'blood type' to list of info? maybe too subtle
%:   • list of best fortune cookies? maybe scanned? 
%:   • link to ridiculous photos of east lansing, maybe just by clicking on
%:     'EL'? 
%:   • on teaching page, maybe mention hampshire stuff, including the crazy
%:     course?
%:   • a FAQ thing including how to pronunce name; what's the deal on the
%:     dept name; what can I do with a linguistics major, etc.
%:     

%This is all work stuff. If you want to know about me personally, then%
%, uh, %seriously, you really need find to someone more interesting to cyberstalk.

%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki
|DESCRIPTION|: Marcin Morzycki's webpage. Recent work, syllabi, etc.
|KEYWORDS|: Marcin Morzycki, linguistics, semantics, syntax, adverbials, modification, adjectives, adverbs, modifiers, degree, degree modifier, comparison, comparative, metalinguistic, almost, approximative, whole,  measure phrase, imprecision, pragmatic halo, quantifier float, extreme adjective, nonrestrictive, scale, scalarity, galore, expressive meaning

|ROOT|: ./
|FILEURL|: http://morzycki.github.io/

%: ———————————————————————————————————————————————————————————————————————————
