
Morzycki, Marcin. 2008. *['Degree Modification of Gradable Nouns: Size Adjectives and Adnominal Degree Morphemes'][deg_nouns]*. Appeared in 2009 in _Natural Language Semantics_ 17(2), 175–203. (The link is to a pre-publication draft. You can find the final version [here][deg_nouns_final].) <a class="bib" href="http://msu.edu/~morzycki/work/bib/morzycki_idiot.bib">BibTeX</a> 

(abs): Degree readings of size adjectives, as in _big stamp-collector_, cannot be explained as merely a consequence of vagueness or as an extra-grammatical phenomenon. Rather, they reflect the grammatical architecture of nominal gradability. Such readings are available only for size adjectives in attributive positions, and systematically only for adjectives that predicate bigness. These restrictions can be understood as part of a broader picture of gradable NPs in which adnominal degree morphemes---often overt---play a key role, analogous to their role in AP. Size adjectives acquire degree readings through a degree morpheme similar to the one that licenses measure phrases in AP. Its syntax gives rise to positional restrictions on the availability of these readings, and the semantics of degree measurement interacts with the scale structure of size adjectives to give rise to restrictions on the adjective itself. 

[NALS]: http://www.springerlink.com/content/102969/
[deg_nouns_final]: http://dx.doi.org/10.1007/s11050-009-9045-7
[deg_nouns]: http://msu.edu/~morzycki/work/papers/deg_nouns.pdf

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; &lsquo;Degree Modification of Gradable Nouns: Size Adjectives and Adnominal Degree Morphemes&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: degree modification, gradability, nominal gradability, scale structure, size adjectives

|ABSTRACT|: Degree readings of size adjectives, as in 'big stamp-collector', cannot be explained as merely a consequence of vagueness or as an extra-grammatical phenomenon. Rather, they reflect the grammatical architecture of nominal gradability. Such readings are available only for size adjectives in attributive positions, and systematically only for adjectives that predicate bigness. These restrictions can be understood as part of a broader picture of gradable NPs in which adnominal degree morphemes---often overt---play a key role, analogous to their role in AP. Size adjectives acquire degree readings through a degree morpheme similar to the one that licenses measure phrases in AP. Its syntax gives rise to positional restrictions on the availability of these readings, and the semantics of degree measurement interacts with the scale structure of size adjectives to give rise to restrictions on the adjective itself.

%: ———————————————————————————————————————————————————————————————————————————
