
Morzycki, Marcin. 2013. *['Vagueness, Degrees, and Gradable Predicates'][chapter]*. This is a chapter of an in-preparation book to be called _Modification_ (in the Cambridge University Press series _Key Topics in Semantics an Pragmatics_). The book is something between a textbook for people with a basic background in semantics and an introductory survey of work on the semantics of modification. [More information about the whole project and additional chapters][book_site] are also available. I'd really appreciate any feedback on this. <a class="bib" href="http://msu.edu/~morzycki/work/book/bib/morzycki_chapter_scales.bib">BibTeX</a>

(abs): The chapter begins with a discussion of vagueness in section 2.
  Section 3 gives a thumbnail sketch of theories of vagueness and gradability
  and explores one approach that hasn't much captured the imagination of
  formal semanticists. Sections 4 and 5 presents two approaches that have.
  Section 6 compares them, considering the question of the status the notion
  'degree' should have in the grammar. Finally, section 7 turns to scalar
  issues in the lexical semantics of adjectives.

[chapter]: http://msu.edu/~morzycki/work/papers/chapter_scales.pdf
[book_site]: http://msu.edu/~morzycki/work/book

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Book chapter: &lsquo;Vagueness, Degrees, and Gradable Predicates&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: vagueness, degrees, gradability, adjectives, antynomy, comparison classes, degree modification, degrees, extension gaps, gradable predicates, imprecision, lexical semantics, scale structure

|ABSTRACT|: The chapter begins with a discussion of vagueness in section 2. Section 3 gives a thumbnail sketch of theories of vagueness and gradability and explores one approach that hasn't much captured the imagination of formal semanticists. Sections 4 and 5 presents two approaches that have. Section 6 compares them, considering the question of the status the notion 'degree' should have in the grammar. Finally, section 7 turns to scalar issues in the lexical semantics of adjectives.

%: ———————————————————————————————————————————————————————————————————————————
