
Morzycki, Marcin. 2013. *[_Modification_][chapter]*. This is a draft of a book in preparation for the the Cambridge University Press series _Key Topics in Semantics an Pragmatics_. It's something between a textbook for people with a basic background in semantics and an introductory survey. You can also get more information about the whole project and download a few chapters individually [here][book_site]. <a class="bib" href="http://msu.edu/~morzycki/work/bib/morzycki_modificationbook.bib">BibTeX</a> 

[chapter]: http://msu.edu/~morzycki/work/papers/modification_book.pdf
[book_site]: http://msu.edu/~morzycki/work/book

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Modification Book Manuscript

|KEYWORDS|: adjectives, adverbial readings of adjectives, adverb(ial)s, antonymy, comparatives, degree constructions, degree modification, degrees, equatives, gradability, imprecision, intersective modifiers, introductory semantics, lexical semantics, manner adverbials, nonrestrictive modification, predicate modifiers, predicative adjectives, scalarity, scale structure, speaker-oriented adverbials, speech-act adverbials, subject-oriented adverbials, subsective modifiers, superlatives, vagueness

|ABSTRACT|: This book is something between a textbook for people with a basic background in semantics and an introductory survey of work on the semantics of modification. Chapters: 1 Introduction; 2 The Lexical Semantics of Adjectives: More Than Just Scales; 3 Vagueness, Degrees, and Gradable Predicates; 4 Comparatives and Their Kin; 5 Adverbs; 6 Crosscategorial Concerns; 7 Taking Stock.

|DESCRIPTION|: Manuscript of a book on the semantics of modification. 

%: ———————————————————————————————————————————————————————————————————————————
