
Morzycki, Marcin. 2013. *['The Lexical Semantics of Adjectives: More Than Just Scales'][chapter]*. This is a chapter of an in-preparation book to be called _Modification_ (in the Cambridge University Press series _Key Topics in Semantics an Pragmatics_). The book is something between a textbook for people with a basic background in semantics and an introductory survey of work on the semantics of modification. [More information about the whole project and additional chapters][book_site] are also available. I'd really appreciate any feedback on this. <a class="bib" href="http://msu.edu/~morzycki/work/book/bib/morzycki_chapter_notscales.bib">BibTeX</a> 

(abs): One could be forgiven for getting the impression that the semantics of adjectives is, above all, the semantics of scales. Yet this would be a misimpression, as this chapter strives to demonstrate. It is about the lexical semantics of adjectives, but it is *not* about scales. Section 2 presents a typology of adjectives according the effect they have on nouns they modify. Section 3 sketches various theoretical approaches that shed light on that typology. Section 4 begins the exploration of particular analytically-tractable classes of adjectives, focusing on adjectives that interact in interesting ways with their nouns. Section 5 continues the exploration of adjective classes, but shifts the focus to adjectives with surprising scope properties. Finally, section 6 considers additional issues closely linked to the syntax of adjectives, including their relative order and the positions they can occupy.

[chapter]: http://msu.edu/~morzycki/work/papers/chapter_notscales.pdf
[book_site]: http://msu.edu/~morzycki/work/book

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Book chapter: &lsquo;The Lexical Semantics of Adjectives: More Than Just Scales&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: modification, adjectives, subsective modifiers, lexical semantics, variation, adverbial readings of adjectives, predicate modifiers, frequency adjectives, attributive adjectives, predicative adjectives

|ABSTRACT|: One could be forgiven for getting the impression that the semantics of adjectives is, above all, the semantics of scales. Yet this would be a misimpression, as this chapter strives to demonstrate. It is about the lexical semantics of adjectives, but it is not about scales. Section 2 presents a typology of adjectives according the effect they have on nouns they modify. Section 3 sketches various theoretical approaches that shed light on that typology. Section 4 begins the exploration of particular analytically-tractable classes of adjectives, focusing on adjectives that interact in interesting ways with their nouns. Section 5 continues the exploration of adjective classes, but shifts the focus to adjectives with surprising scope properties. Finally, section 6 considers additional issues closely linked to the syntax of adjectives, including their relative order and the positions they can occupy.

%: ———————————————————————————————————————————————————————————————————————————
