
Morzycki, Marcin. 2013. *['Adverbs'][chapter]*. This is a chapter of an in-preparation book to be called _Modification_ (in the Cambridge University Press series _Key Topics in Semantics an Pragmatics_). The book is something between a textbook for people with a basic background in semantics and an introductory survey of work on the semantics of modification. [More information about the whole project and additional chapters][book_site] are also available. 
<a class="bib" href="http://msu.edu/~morzycki/work/book/bib/morzycki_chapter_adverbs.bib">BibTeX</a> 

(abs): This chapter is devoted to adverbs, a highly heterogenous class of modifiers that presents a variety of vexing problems. Section 2 considers how some taxonomical organization can be introduced into the chaos of adverbs. Section 3 then takes the first steps toward an analysis, wrestling with foundational compositional questions and a puzzle involving intensionality. Section 4 examines two classes of adverbs (manner and subject-oriented) in more detail. Section 5 turns to adverbs that occur higher in the clause. Section 6 introduces some facts and tools relevant to locative adverbials. Section 7 turns to the ill-understood phenomenon of adverbs as modifiers of adjectival projections. Section 8 mostly just sets aside temporal and quantificational adverbials. Section 9 concludes by revisiting the questions of the relative order of adverbs.

[chapter]: http://msu.edu/~morzycki/work/papers/chapter_adverbs.pdf
[book_site]: http://msu.edu/~morzycki/work/book

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Book chapter: &lsquo;Adverbs&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: adverbs, epistemic adverbials, evaluative adverbials, events, comparison classes, conventional implicature, degree adverbials, degree modifiers, manner adverbials, speaker-oriented adverbials, speech-act adverbials, subject-oriented adverbials, adverb order

|ABSTRACT|: This chapter is devoted to adverbs, a highly heterogenous class of modifiers that present a variety of vexing problems. Section 2 considers how some taxonomical organization can be introduced into the chaos of adverbs. Section 3 then takes the first steps toward an analysis, wrestling with foundational compositional questions and a puzzle involving intensionality. Section 4 examines two classes of adverbs (manner and subject-oriented) in more detail. Section 5 turns to adverbs that occur higher in the clause. Section 6 introduces some facts and tools relevant to locative adverbials. Section 7 turns to the ill-understood phenomenon of adverbs as modifiers of adjectival projections. Section 8 mostly just sets aside temporal and quantificational adverbials. Section 9 concludes by revisiting the questions of the relative order of adverbs.

%: ———————————————————————————————————————————————————————————————————————————
