
Morzycki, Marcin. 2010. *['Adjectival Extremeness: Degree Modification and
Contextually Restricted Scales'][extreme]*. To appear in _Natural Language
and Linguistic Theory_. The link is to a not-quite-final version. <a
class="bib"
href="http://msu.edu/~morzycki/work/bib/morzycki_extreme.bib">BibTeX</a>

(abs): This paper argues that degree modifiers such as _flat-out_, _downright_, _positively_, and _straight-up_ constitute a distinct natural class specialized for modifying extreme adjectives (such as _gigantic_, _fantastic_, or _gorgeous_), and that extreme adjectives themselves come in two varieties: ones that encode extremeness as part of their lexical semantics and ones that can acquire it on the basis of contextual factors. These facts suggest that a theory is required of what it means for an adjective to be 'extreme' in the relevant sense. I propose one, based on the idea that in any given context, we restrict our attention to a particular salient portion of a scale. To reflect this, I suggest that quantification over degrees is---like quantification in other domains---contextually restricted. Extreme adjectives and corresponding degree modifiers can thus both be understood as a means of signaling that a degree lies outside a contextually-provided range. 

[extreme]:
  http://msu.edu/~morzycki/work/papers/extreme_2010.pdf
[extreme_degs_cls]:
  http://msu.edu/~morzycki/work/papers/extreme_cls.pdf
[NLLT]: http://www.springerlink.com/content/102968/

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: &lsquo;Adjectival Extremeness: Degree Modification and Contextually Restricted Scales&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: degree modifiers, gradability, extreme adjectives, domain restrictions, context sensitivity, scale structure

|ABSTRACT|: This paper argues that degree modifiers such as 'flat-out', 'downright', 'positively', and 'straight-up' constitute a distinct natural class specialized for modifying extreme adjectives (such as 'gigantic', 'fantastic', or 'gorgeous'), and that extreme adjectives themselves come in two varieties: ones that encode extremeness as part of their lexical semantics and ones that can acquire it on the basis of contextual factors. These facts suggest that a theory is required of what it means for an adjective to be 'extreme' in the relevant sense. I propose one, based on the idea that in any given context, we restrict our attention to a particular salient portion of a scale. To reflect this, I suggest that quantification over degrees is---like quantification in other domains---contextually restricted. Extreme adjectives and corresponding degree modifiers can thus both be understood as a means of signaling that a degree lies outside a contextually-provided range.

%: ———————————————————————————————————————————————————————————————————————————
