
Morzycki, Marcin. 2010. *['Quantification Galore'][galore_LI]*. Appeared in 2011 in _[Linguistic Inquiry][LI]_ 42(4): 671--682. A pre-publication draft is [here][galore]. <a class="bib" href="http://msu.edu/~morzycki/work/bib/morzycki_galore.bib">BibTeX</a> 

  (abs): This squib examines the grammar of _galore_, arguing that it is a
  quantificational determiner that operates exclusively on kinds. In doing so
  it realizes a possible determiner denotation that one might independently
  expect to occur in English in the crosslinguistic framework proposed in
  Chierchia (1998).

[galore]: http://msu.edu/~morzycki/work/papers/galore_squib.pdf
[galore_LI]: http://dx.doi.org/10.1162/LING_a_00065
[LI]: http://www.mitpressjournals.org/loi/ling

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: &lsquo;Quantification Galore&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: galore, quantification, kinds, variation

|ABSTRACT|: This squib examines the grammar of 'galore', arguing that it is a quantificational determiner that operates exclusively on kinds. In doing so it realizes a possible determiner denotation that one might independently expect to occur in English in the crosslinguistic framework proposed in Chierchia (1998).

%: ———————————————————————————————————————————————————————————————————————————
