
Morzycki, Marcin. 2010.  *['Expressive Modification and the Licensing of Measure Phrases'][goddamn_MP_final]*. Appeared in 2011 in the _[Journal of Semantics][JoS]_ 28(3): 401--411. A pre-publication draft is [here][goddamn_MP]. (This is identical to what was previously titled 'Expressive Modifiers, Measure Phrases, and Degree Types'.) <a class="bib"
href="http://msu.edu/~morzycki/work/bib/morzycki_goddamn_MP.bib">BibTeX</a>

  (abs): This squib points out that adjectives with measure phrases are
  incompatible with expressive modifiers such as _goddamn_. It shows that
  this otherwise mysterious fact can be explained relatively straightforwardly
  if, as Schwarzschild (2005) has argued, positive adjectives can support
  measure phrases only as the result of a type-shifting rule in the lexicon.

[goddamn_MP]:
  http://msu.edu/~morzycki/work/papers/goddamn_MP.pdf
[goddamn_MP_final]: http://dx.doi.org/10.1093/jos/ffq021
[goddamn_MP]: papers/goddamn_MP.pdf
[JoS]: http://jos.oxfordjournals.org

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: &lsquo;Expressive Modification and the Licensing of Measure Phrases&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: expressive meaning, adjectives, degree modification, measure phrases

|ABSTRACT|: The aim of this squib is to call attention to the incompatibility of measure phrases and expressive modifiers such as 'goddamn', and to demonstrate that this incompatibility can be explained straightforwardly by supplementing a somewhat modified version of the approach to measure-phrase interpretation proposed in Schwarzschild (2005) with a few minimal assumptions about what expressive modifiers mean.

%: ———————————————————————————————————————————————————————————————————————————
