
Morzycki, Marcin. 2008. *['Metalinguistic Comparison in an Alternative Semantics for Imprecision'][metaling_NELS]*. Appeared in 2009 in Muhammad Abdurrahman, Anisa Schardl, and Martin Walkow, eds. _Proceedings of NELS 38_. GLSA Publications, Amherst, Mass. There is also an extended [more recent version][metaling_2010] of this paper above that develops this more fully. You should probably look at that rather than this proceedings version. <a class="bib" href="http://msu.edu/~morzycki/work/bib/morzycki_metaling_nels.bib">BibTeX</a> 

(abs): ‘Metalinguistic’ comparatives such as _more dumb than ugly_ or _more a semanticist than a syntactician_ have until recently remained largely unexamined in the formal semantics literature (the principal exception is [Giannakidou and Stavrou 2007][anastasia_paper]). This paper provides an analysis of such structures built on the intuition that they compare not along scales introduced by gradable adjectives---as ordinary comparatives do---but rather along a scale of (im)precision, or of how much pragmatic 'slack' must be afforded to judge an expression 'close enough to true'. This is expressed by reformulating the pragmatic-halos theory of imprecision (Lasersohn 1999) in terms of a Hamblin-style alternative semantics (Hamblin 1973) in a way that allows degrees of imprecision---roughly, 'halo size'---to be directly compared. 

  [metaling_NELS]: http://msu.edu/~morzycki/work/papers/metaling_comp_NELS.pdf
  [anastasia_paper]: http://home.uchicago.edu/~giannaki/pubs/final.para.pdf
  [metaling_2010]: http://semanticsarchive.net/Archive/2FkNTExY

%: ———————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; &lsquo;Metalinguistic Comparison in an Alternative Semantics for Imprecision&rsquo;

|DESCRIPTION|: Link to a copy of the paper.

|KEYWORDS|: comparatives, imprecision, metalinguistic phenomena, degrees, alternatives

|ABSTRACT|: 'Metalinguistic' comparatives such as 'more dumb than ugly' or 'more a semanticist than a syntactician' have until recently remained largely unexamined in the formal semantics literature (the principal exception is Giannakidou and Stavrou 2007). This paper provides an analysis of such structures built on the intuition that they compare not along scales introduced by gradable adjectives---as ordinary comparatives do---but rather along a scale of (im)precision, or of how much pragmatic 'slack' must be afforded to judge an expression 'close enough to true'. This is expressed by reformulating the pragmatic-halos theory of imprecision (Lasersohn 1999) in terms of a Hamblin-style alternative semantics (Hamblin 1973) in a way that allows degrees of imprecision---roughly, 'halo size'---to be directly compared.

%: ———————————————————————————————————————————————————————————————————————————
