|MONTH|: Sept.
|YEAR|: 11

Research interests
——————————————————

Broadly, my research interests are *semantics and its interface with syntax*.

Many of the issues I've worked on over the years are related in one way or another to *modification*---adjectives, adverbials, manners, degree expressions, measure phrases, events, among others---and I wrote a [book][book] on the topic, but it's not actually altogether clear that this label designates a single natural class of empirical phenomena,
% rather than a rather diverse grab bag, 
% so I've isolated a few more specific themes:
so are some more specific overlapping themes:

  [almostSALT]: ../work/index.html#almostSALT
  [bigidiot]: ../work/index.html#deg_nouns_final
  [book]: ../work/book
  [compositeMPs]: ../work/index.html#composite_MPs  
  [compositeMPsSUB]: ../work/index.html#compositeMPsSUB
  [degreekinds]: ../work/index.html#degree_kinds_paper
  [DPadv]: ../work/index.html#DPadvwccfl
  [extreme]: ../work/index.html#extreme
  [extremefinal]: ../work/index.html#extreme_final
  [faces]: ../work/index.html#faces_of_nom_deg_mod
  [hotzesquib]: ../work/index.html#hotzesquib
  [ktquestionssub]: ../work/index.html#ktquestionssub
  [leipzig]: ../work/index.html#leipzig
  [metaling]: ../work/index.html#metaling_NALS
  [MPsvectors]: ../work/index.html#MPs_vectors
  [nominalizationsSuB]: ../work/index.html#nominalizationsSuB
  [nonlocal]: ../work/index.html#nonlocal
  [nonlocalSUB]: ../work/index.html#nonlocalSUB
  [piano]: ../work/index.html#piano
  [propositionalhow]: ../work/index.html#propositionalhow
  [ranges]: ../work/index.html#ranges  
  [rangesSALT]: ../work/index.html#rangesSALT
  [ryan]: https://linguistics.ubc.ca/profile/ryan-bochnak
  [single]: ../work/index.html#single
  [takso]: ../work/index.html#takso
  [wholesshort]: ../work/index.html#wholesshort
  [zeroSALT]: ../work/index.html#zeroSALT

• *Measurement, mathematical language, and numerals*. With [Ryan
  Bochnak][ryan], I currently have a Social Sciences and Humanities Research
  Council of Canada grant to explore this topic, especially in understudied
  languages and crosslinguistically (and we very much welcome applications
  from potential grad students interested in this!). I've worked
  with Adam Gobeski on ranges (e.g. _from six to twelve monkeys_) in [this
  paper][ranges] and [this older one][rangesSALT], and on and [composite
  measure phrases][compositeMPsSUB] (e.g. _one in four_). I've also worked on
  _[single][single]_. In much older work I examined 
  % [verbal][DPadv] and
  [crosscategorial measure phrases][MPsvectors].

	% don't forget ancient wccfl paper
	% mention advising Gobeski, Anderson?
  
• *Modifier questions*. With various collaborators, I have explored how 
  [modifier questions][ktquestionssub] are composed in Ktunaxa, on [propositional readings of _how_][propositionalhow]
  in English, and 
  % [implicitly degree-oriented questions][implicitdegree] 
  implicitly degree-oriented questions
  in English and Ktunaxa. 
  %More recently I've been thinking about readings of _why_.
  
• *Natural language ontology*. With collaborators I have proposed treating
  [degrees as Carlsonian kinds of states][degreekinds], and in [older
  work][takso] introducing manners as a type in the model by treating
  them as [event kinds][takso]. I've also worked on [the ontology of
  scales][compositeMPsSUB], on [null individuals][zeroSALT], and on [the
  distinction][nominalizationsSuB] between degree concepts and abstract mass
  qualities.
  
• *Nominal gradability, degree modification, and gradability across
  categories*. I've examined how [size adjectives contribute to
  nominal gradability][bigidiot] (_big idiot_), and how [other degree
  expressions][faces] do too. More recently I've worked on [degree
  nominalizations][nominalizationsSuB]. An older paper considers [extreme
  degree modifiers][extremefinal] like _flat-out_ and [another][leipzig],
  ad-adjectival adverbs like _remarkably_. I've also worked on [metalinguistic
  comparatives][metaling], which have a crosscategorial distribution. [This
  ancient paper][almostSALT] draws attention to crosscategorial uses of
  particles like _almost_.

	% paper with curt
	% almost paper
	% Ai T.
  
• *Manner modification*. More or less recently I've worked on why manner
  descriptions tend to be [unexpectedly definite][hotzesquib] and how manner
  and other modifier questions are formed in [Ktunaxa][ktquestionssub].
  With collaborators, I've proposed that 'manners' can be understood
  as kinds of events. This has also come up in [this paper focused on
  degrees][degreekinds], but the idea dates originally from [this][takso]
  nearly quarter-century old proceedings paper. I've also worked on why [_how_
  often gets non-manner readings][propositionalhow].

• *Adjectival lexical semantics and nonlocal readings of adjectives*.
  This paper attempts [a general theory of nonlocal readings][nonlocal],
  and you can also look at [this earlier attempt][nonlocalSUB] or an early
  assessment of the data in my [book][book]. They also come up with respect to
  _[single][single]_ and [bare singulars][piano] in English. Years ago I worked
  on [extreme adjectives][extremefinal] (also, in an earlier incarnation,
  [here][extreme]). I've also worked on adjectives like _[whole][wholesshort]_.

	% maybe sub nominalizations goes here too?



% • *Ktunaxa*. Lorem ipsum dolor sit
%   amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
%   et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
%   ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
%   dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
%   pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
%   officia deserunt mollit anim id est laborum.
  
% ### Ktunaxa
% 
% - questions etc
% - paper with anne
% - also advising Rose and Starr and working with Anne and grant with Ryan
% 
% ### Numerals, measurement, and mathematical language
% 
% don't forget ancient wccfl paper
% mention advising Gobeski, Anderson
% 
% 
% ### Manner
% 
% ancient paper
% ktunaxa questions paper
% hotze squib
% propositional how (which isn't actually about manner)
% curt paper
% 
% 
% ### Natural language ontology
% 
% event kinds
% state kinds
% degrees and scales (composite MPs)
% zero
% sub paper
% 
% ### Degree modification and nominal gradability
% 
% almost paper
% adnominal degree modification
% Ai T.
% 
% 
% #### Questions
% 
% Daniel
% Starr & Anne
% Starr, me, & Kate
% Starr & me
% 
% 
% ### Nonlocal readings of adjectives
% 
% SuB talk 
% occasional paper
% also cite book
% 
% 
% incorporate PhD students as much as possible!


% Most of my work centers on various aspects of the grammar of modification. 
% %This is of course a broad topic, and it's not at all obvious that it constitutes a natural class of phenomena---but ultimately whether it does so is itself an empirical question. 
% It's not at all obvious that this actually constitutes a natural class of phenomena, but whether it does so is an interesting question in itself.
% One issue I have been thinking about in the last few years is how gradability works in non-adjectival syntactic contexts. I've also been working on degree modifiers, including both the more familiar sort found in the extended AP and what I believe to be their analogues elsewhere. Other topics I have worked on less recently include nonrestrictive modification, measure phrases, modification of quantifiers, adverbial modification, expressive meaning, and apparently semantic restrictions on modifier order.
% %Across these areas, there are a number of more general recurring themes. These include fine-grained lexical semantic distinctions, semantic parallels across syntactic categories, the semantic effects of syntactic position, and the nature of degrees. 
% Much of my work also reflects 
% %a methodological proclivity toward 
% %a proclivity to work on
% a fondness for
% %an predilection for
% %an aesthetic predisposition to work on
% %an interest in 
% phenomena that might be regarded as peripheral but 
% %often 
% turn out to be productive 
% % quite regular? systematic?
% and, in the ideal case, to bear on more general theoretical questions. 
% %I'm also broadly interested in psycholinguistic and acquisition questions, though this has so far taken the form of occasional participation in the work of others.
% %, and in this respect in the nature of productivity and peripherality themselves.
% %Behind this methodological predisposition, though, there are some empirical hypotheses: that 'peripheral' phenomena reflect deeper grammatical truths as much as less peripheral ones do; there is more productivity behind small-scale regularities than one might think;
% %%that small-scale regularities turn out to be productive more often than one might think; 
% %and that it is not in fact straightforward to determine precisely which phenomena 
% %%patterns
% %should be regarded as peripheral.

%: Q: add acquisition stuff? something about how peripheral phenomena reflect
%:    semantic variation in a way that's not so different from
%:    cross-linguistic work? (wtf does this actually mean, anyway?)

% #### For non-linguist humans ####
% 
% %If you are not a linguist, I forgive you, and you may benefit from some elaboration of the above. What theoretical linguists in general do is try to figure out what exactly it is you know when you know a language. One aspect of this is knowledge of how the meanings of sentences are assembled from the meanings of words. That's what I work on. I seem to have fixated on various puzzles involving modifiers---bits of a sentence that can usually be left out without making the sentence sound strange. That's a very broad topical focus, but there is also an intellectual aesthetic running through a lot of my work: I like superficially small, weird, and idiosyncratic patterns that nevertheless turn out to be systematic and (hopefully) shed light on larger theoretical issues. 
% %If you are not a linguist, I forgive you, and you may benefit from some elaboration on the above. 
% What theoretical linguists in general do is try to figure out what exactly it is you know when you know a language. One aspect of this is knowledge of meaning. That's what I work on. I usually think about how the meanings of sentences are assembled from the meanings of words, and what this tells us about the meanings of the words themselves. I seem to have fixated on various puzzles involving modifiers---bits of a sentence that, in general, can be left out without making the sentence sound strange. That's a broad topical focus, but there is also an intellectual aesthetic running through a lot of my work: 
% %an enthusiasm for 
% I really like 
% linguistic phenomena that might superficially seem minor or idiosyncratic but 
% %superficially 
% %minor
% %%small, 
% %%weird, 
% %and idiosyncratic linguistic phenomena 
% that nevertheless turn out to be systematic and (hopefully) shed light on larger theoretical issues. 
% 
% #### But never mind this… ####
% 
% Really, in order to get a sense of what I do, you should just look at [my work](../work) instead.
% 
% %: include a thing on intellectual history?
% %My dissertation adviser was Angelika Kratzer, and my committee also included Barbara Partee, Kyle Johnson, and Lisa Matthewson. Among the people who first introduced me to linguistics were Sandy Chung (my undergrad thesis adviser), Jim McCloskey, Donka Farkas, Judith Aissen, and Bill Ladusaw.
% %I first encountered linguistics as an undergrad at UC Santa Cruz, 
% %Anna Maria Di Sciullo


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Research interests
|DESCRIPTION|: Marcin Morzycki's research interests.
|KEYWORDS|: Morzycki, Marcin Morzycki, linguistics, semantics, syntax, adverbial, modification, adjectival, adverb, adjective, modifier, degree, degree modifier, comparison, comparative, metalinguistic, almost, approximative, whole, entire, measure phrase, imprecision, pragmatic halo, quantifier float, extreme adjective, nonrestrictive, scale, scalarity, galore, expressive meaning

|ROOT|: ../
|FILEURL|: http://morzycki.github.io/interests

%: ———————————————————————————————————————————————————————————————————————————

