|MONTH|: Sept.
|YEAR|: 11

Research interests
——————————————————

#### In five words ####

Semantics, syntax, and their interface.

#### In slightly more than five words ####

Most of my work centers on various aspects of the grammar of modification. 
%This is of course a broad topic, and it's not at all obvious that it constitutes a natural class of phenomena---but ultimately whether it does so is itself an empirical question. 
It's not at all obvious that this actually constitutes a natural class of phenomena, but whether it does so is an interesting question in itself.
One issue I have been thinking about in the last few years is how gradability works in non-adjectival syntactic contexts. I've also been working on degree modifiers, including both the more familiar sort found in the extended AP and what I believe to be their analogues elsewhere. Other topics I have worked on less recently include nonrestrictive modification, measure phrases, modification of quantifiers, adverbial modification, expressive meaning, and apparently semantic restrictions on modifier order.
%Across these areas, there are a number of more general recurring themes. These include fine-grained lexical semantic distinctions, semantic parallels across syntactic categories, the semantic effects of syntactic position, and the nature of degrees. 
Much of my work also reflects 
%a methodological proclivity toward 
%a proclivity to work on
a fondness for
%an predilection for
%an aesthetic predisposition to work on
%an interest in 
phenomena that might be regarded as peripheral but 
%often 
turn out to be productive 
% quite regular? systematic?
and, in the ideal case, to bear on more general theoretical questions. 
%I'm also broadly interested in psycholinguistic and acquisition questions, though this has so far taken the form of occasional participation in the work of others.
%, and in this respect in the nature of productivity and peripherality themselves.
%Behind this methodological predisposition, though, there are some empirical hypotheses: that 'peripheral' phenomena reflect deeper grammatical truths as much as less peripheral ones do; there is more productivity behind small-scale regularities than one might think;
%%that small-scale regularities turn out to be productive more often than one might think; 
%and that it is not in fact straightforward to determine precisely which phenomena 
%%patterns
%should be regarded as peripheral.

%: Q: add acquisition stuff? something about how peripheral phenomena reflect
%:    semantic variation in a way that's not so different from
%:    cross-linguistic work? (wtf does this actually mean, anyway?)

#### For non-linguist humans ####

%If you are not a linguist, I forgive you, and you may benefit from some elaboration of the above. What theoretical linguists in general do is try to figure out what exactly it is you know when you know a language. One aspect of this is knowledge of how the meanings of sentences are assembled from the meanings of words. That's what I work on. I seem to have fixated on various puzzles involving modifiers---bits of a sentence that can usually be left out without making the sentence sound strange. That's a very broad topical focus, but there is also an intellectual aesthetic running through a lot of my work: I like superficially small, weird, and idiosyncratic patterns that nevertheless turn out to be systematic and (hopefully) shed light on larger theoretical issues. 
%If you are not a linguist, I forgive you, and you may benefit from some elaboration on the above. 
What theoretical linguists in general do is try to figure out what exactly it is you know when you know a language. One aspect of this is knowledge of meaning. That's what I work on. I usually think about how the meanings of sentences are assembled from the meanings of words, and what this tells us about the meanings of the words themselves. I seem to have fixated on various puzzles involving modifiers---bits of a sentence that, in general, can be left out without making the sentence sound strange. That's a broad topical focus, but there is also an intellectual aesthetic running through a lot of my work: 
%an enthusiasm for 
I really like 
linguistic phenomena that might superficially seem minor or idiosyncratic but 
%superficially 
%minor
%%small, 
%%weird, 
%and idiosyncratic linguistic phenomena 
that nevertheless turn out to be systematic and (hopefully) shed light on larger theoretical issues. 

#### But never mind this… ####

Really, in order to get a sense of what I do, you should just look at [my work](../work) instead.

%: include a thing on intellectual history?
%My dissertation adviser was Angelika Kratzer, and my committee also included Barbara Partee, Kyle Johnson, and Lisa Matthewson. Among the people who first introduced me to linguistics were Sandy Chung (my undergrad thesis adviser), Jim McCloskey, Donka Farkas, Judith Aissen, and Bill Ladusaw.
%I first encountered linguistics as an undergrad at UC Santa Cruz, 
%Anna Maria Di Sciullo


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Research interests
|FILEURL|: http://msu.edu/~morzycki/interests

|DESCRIPTION|: Marcin Morzycki's research interests.

|KEYWORDS|: Morzycki, Marcin Morzycki, linguistics, semantics, syntax, adverbial, modification, adjectival, adverb, adjective, modifier, degree, degree modifier, comparison, comparative, metalinguistic, almost, approximative, whole, entire, measure phrase, imprecision, pragmatic halo, quantifier float, extreme adjective, nonrestrictive, scale, scalarity, galore, expressive meaning

%: ———————————————————————————————————————————————————————————————————————————

