|MONTH|: July
|YEAR|: 24


CV
——

Here's my [CV](morzycki_cv.pdf). 


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Students
|DESCRIPTION|: Marcin’s CV.
|KEYWORDS|: Marcin Morzycki, linguistics, cv

|ROOT|: ../
|FILEURL|: http://morzycki.github.io/cv

%: ———————————————————————————————————————————————————————————————————————————

