
Teaching
————————

%I'm currently on sabbatical and not doing any teaching. Here are the syllabi for some classes I regularly teach:

In fall '18:

	• [LIN 437: Semantics & Pragmatics](437/syllabus.pdf)
	• [LIN 837: Advanced Semantics & Pragmatics](837/syllabus.pdf)

I also teach:

	• [LIN 401: Introduction to Linguistics](401/syllabus.pdf)
  • [LIN 892: Seminar in Linguistics](892/syllabus.pdf) 
    %   In addition to a general component that remains constant from year to 
    %   year, this course covers several more specific topics that vary. 

A more or less teaching-related fact: I recently finished a draft of [a book](../work/book) that's something between an advanced textbook for people who already have a background in semantics and an introductory survey of work on the semantics of modification.
 
%In Spring '11:
%
% • [LIN 437: Semantics & Pragmatics](437/syllabus.pdf) 
% • [LIN 892: Seminar in Linguistics](892/syllabus.pdf). Topic: 
%   cross-categorial phenomena and parallels across types and categories. 

%: put 'how to read' handout up someday?

%I don’t have teaching stuff from other courses on-line, but such things might in principle be available by email.

%If you're an undergrad wondering what one can do in life with a linguistics degree, you should probably find out and then let me know. You may want to start your research into this topic here or here.


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Teaching
|DESCRIPTION|: Some of Marcin Morzycki's syllabi.
|KEYWORDS|: teaching, syllabi

%: ———————————————————————————————————————————————————————————————————————————
