
Teaching
————————

%I'm currently on sabbatical and not doing any teaching. Here are the syllabi for some classes I regularly teach:

At UBC: 

	• I recently taught [LING 425/525](425525/syllabus.pdf), a mixed undergrad-grad advanced semantics course.
	• Over the summer, I'm teaching [LING 201](201/syllabus.pdf), an introduction to syntax and semantics.

At Michigan State, I regularly used to teach these:
	
	• [LIN 401: Introduction to Linguistics](401/syllabus.pdf)
	• [LIN 437: Semantics & Pragmatics](437/syllabus.pdf)
	• [LIN 837: Advanced Semantics & Pragmatics](837/syllabus.pdf) (rotating combinations of topics)
	• [LIN 892: Seminar in Linguistics](892/syllabus.pdf) (varying topics)
    %   In addition to a general component that remains constant from year to 
    %   year, this course covers several more specific topics that vary. 

And, since it's teaching-related and I can't resist, here's a link [the book](../work/book) again. 
 

%I don’t have teaching stuff from other courses on-line, but such things might in principle be available by email.

%If you're an undergrad wondering what one can do in life with a linguistics degree, you should probably find out and then let me know. You may want to start your research into this topic here or here.


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Teaching
|DESCRIPTION|: Some of Marcin Morzycki's syllabi.
|KEYWORDS|: teaching, syllabi

%: ———————————————————————————————————————————————————————————————————————————
