
Links
—————

%You should visit the Michigan State [semantics research group][msusemantics] site.

Other miscellaneous linguistics-related stuff:

  [msusemantics]: http://msusemantics.weebly.com
	• [semanticsarchive.net](http://semanticsarchive.net), the best place to 
	  look for semantics papers online, apart from Google 
	• some semantics journals: 
		• _[Natural Language Semantics][NALS]_
		• _[Journal of Semantics][JoS]_
		• _[Linguistics & Philosophy][LP]_
		• _[Semantics & Pragmatics][SandP]_
	• some semantics conferences: 
		• [SALT (Semantics and Linguistic Theory)][SALT] 
		• [Sinn und Bedeutung][SuB] 
		• [SULA (Semantics of Under-represented Languages in the 
		  Americas)][SULA] 
		• the [Amsterdam Colloquium][Amsterdam] 
		• [SWAMP][SWAMP] ('Semantics Workshop of the American Midwest and 
		  Prairies', formerly 'In Search of Meaning in the Midwest', formerly 
		  the Midwest Workshop on Semantics) 
	• some other journals with syntax/semantics in them: 
		• _[Natural Language & Linguistic Theory][NLLT]_ 
		• _[Linguistic Inqiury][LI]_ 
		• _[Lingua][Lingua]_
		• _[Theoretical Linguistics][TheorLing]_
		• _[Language][Language]_
		• _[Syntax][Syntax]_
	• some other conferences with syntax/semantics in them: 
		• [WCCFL][WCCFL] (West Coast Conference on Formal Linguistics)
		• [NELS][NELS] (North East Linguistic Society)
		• [GLOW][GLOW] (Generative Linguistics in the Old World)
%	• Ana Arregui's handy [list][ana_resources] of semantics journals, 
%	  conferences, etc. 
%	• Kai von Fintel's list of online semantics [resources][fintel_resources] 

Other things:

  • Michigan State's apparently proud tradition of [unsafe 
    buildings](http://archives.msu.edu/collections/buildings.php):
    <blockquote><p>[I]n 1918, as the National Anthem was being played … the
    walls of College Hall began to collapse … Saint's Rest, the first
    dormitory, … burned during the December 1876 vacation … On January
    1, 1919, fire consumed [Williams Hall] … The botanical lab, built in
    1880, was destroyed by fire in 1890. … [T]he first Wells Hall was built
    in 1877 as a dormitory that served 130 students. It burned in 1905 …
    [T]he Engineering Building was the most prominent building on campus when
    on Sunday morning, March 5, 1916, fire destroyed the
    structure …</p></blockquote>
    %: other details:
    %
    %  Built in 1856, College Hall was the first building in America erected
    %  for instruction in scientific agriculture. ... One August day in 1918,
    %  as the National Anthem was being played by the band at a nearby war
    %  trainees retreat, the walls of College Hall began to collapse. Members
    %  of the football team were used to finish tearing down the building.
    %
    %  Built in 1856, Saint's Rest, the first dormitory, is believed to have
    %  been the second building erected on campus.
    %
	• If you're not using [LaTeX](http://en.wikipedia.org/wiki/LaTeX), well, 
	  obviously, you should be. Here is some [LaTeX stuff for 
	  linguists][LaTeX_Penn] that can provide a starting point. 
%     (And for god's sake, don't let the first thing you do be to change the horizontal margins to 1 inch.)
	  %, because you haven't really lived until you've 
	  %proposed an analysis that doesn't work in a paper that doesn't compile 
%	• the person pictured above is %His Holy Majesty
%	  [Gyanendra](http://en.wikipedia.org/wiki/Gyanendra), 
%	  former [god-king][god_king] of Nepal,
%      % incarnation of Vishnu, 
%      suspected [murderer][murder_story], and ['respected wildlife
%      enthusiast'][murder_story]; he was recently [deposed][deposed]
	  % (perhaps the enthusiasm for both wildlife and murder accounts for the
	  % hat?)
	  % (I've found no explanation of the hat/headdress/crown thing; maybe it's 
	  % like a dunce cap for murderers?)
	• I think that [this 
	  essay](http://www.structuredprocrastination.com) by John Perry on 
	  'structured procrastination' may be onto something. You should read it, 
	  precisely because you should do something else instead.
%		it's not the most important thing you 
%	  should be doing. 
%  • this is not actually a link, and I know it's tacky to have an animated
%    gif on one's webpage, but… seriously, just _look_ at this thing!: <p
%    style="text-align:center"><img src="../pix/penguin_slap.gif" title="Plop."
%    alt="Incredibly cool animation of penguins."></p>

[LaTeX_Essex]: http://www.essex.ac.uk/linguistics/clmt/latex4ling
	%: This apparently no longer works.
	
[LaTeX_Penn]: http://www.ling.upenn.edu/advice/latex.html

[murder_story]: http://www.guardian.co.uk/Archive/Article/0,4273,4198139,00.html
[god_king]: http://www.timesonline.co.uk/tol/news/world/article691316.ece
[deposed]: http://www.guardian.co.uk/world/2008/jun/11/nepal

[LP]: http://www.springerlink.com/content/102955/
[NALS]: http://www.springerlink.com/content/102969/
[JoS]: http://jos.oxfordjournals.org
[LI]: http://www.mitpressjournals.org/loi/ling
[NLLT]: http://www.springerlink.com/content/102968/
[Lingua]: http://www.sciencedirect.com/science?_ob=JournalURL&_cdi=5815
[TheorLing]: http://search.ebscohost.com/direct.asp?db=ufh&jid=%222I6%22
[Language]: http://www.jstor.org/journals/00978507.html
[Syntax]: http://www.blackwell-synergy.com/loi/synt
[SandP]: http://semprag.org

%: These need regular updating:
[Amsterdam]: http://www.google.com/search?q=site%3Awww.illc.uva.nl+%22amsterdam+colloquium%22+proceedings
[SuB]: http://www.phil-fak.uni-duesseldorf.de/asw/gfs/english/meetings.html
	%http://www.google.com/search?q=%22sinn+und+bedeutung%22+proceedings
[SULA]: http://www.google.com/search?q=Semantics+Underrepresented+Languages+Americas+SULA
[NELS]: http://www.google.com/search?q=linguistics+nels
[WCCFL]: http://www.cascadilla.com/wccfl.html
[GLOW]: http://glow.uit.no
[SWAMP]: http://msu.edu/~lingorg/swamp
  %:: update this URL!
[SALT]: http://www.google.com/search?q=SALT+semantics+and+linguistic+theory


%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Links
|DESCRIPTION|: Miscellaneous links.
|KEYWORDS|: linguistics, semantics, syntax

%: ———————————————————————————————————————————————————————————————————————————
