|MONTH|: Sept.
|YEAR|: 18


Students
————————

Doctoral students whose committees I've chaired (two are named Ai, coincidentally):

  • *Adam Gobeski*. Dissertation in progress on temporal adverbials and 
    factor phrases. 
  • *[Cara Feldscher](https://msu.edu/~feldsch3)*. Working (among other 
    things) on interpretations of additive expressions like _additional_, 
    which are ambiguous between degree and event-summing readings (e.g. 
    _Floyd traveled an additional six miles the next day_). 
  • *[Josh Herrin](https://herrinjomsu.files.wordpress.com)*. Working (among 
    other things) on superlatives, _of_, and fronting of degree words inside 
    nominals (_the tallest of people_, _so tall (of) a person_). 
  • *[Yan Cong](http://linglang.msu.edu/people/graduate-students/yan-cong)*. 
    Working (among other things) on subjectivity in Mandarin. 
  • *[Ai Taniguchi](http://www.msu.edu/~taniguc7)*. Defended in 2017. 
    Dissertation: _The Formal Pragmatics of Non-At-Issue Intensification in 
    English and Japanese_. Now in a renewable semantics position at 
    [Carleton University](http://carleton.ca/slals/people/taniguchi-ai) in 
    Ottawa. Not identical to Ai Kubota. 
  • *[Curt Anderson](http://curtanderson.github.io)*. Defended in 2016. 
    Dissertation on attenuation, intensification, approximation, and slack 
    regulation. Currently a postdoc at the University of Düsseldorf. 
  • *[Ai Kubota](http://msu.edu/~matsuiai)*. Defended in 2016. Dissertation 
    on evaluative adverbs and related issues in Japanese. Now a postdoc at 
    the National Institute for Japanese Language and Linguistics (NINJAL). 
    Not identical to Ai Taniguchi. 
  • *[Olga Eremina](https://www.hse.ru/en/org/persons/92284721)*. Defended 
    in 2011. Dissertation on indefinites in Russian. Now at the National 
    Research University Higher School of Economics in Moscow. Most recently 
    teaching at Middlebury and Dartmouth Colleges. 
  • *[Irina Agafonova](http://www.msu.edu/~agafonov)*. Defended in 2010. 
    Dissertation on conjunction in Russian. Her work had a computational 
    component, on which she was advised by [John 
    Hale](http://courses.cit.cornell.edu/jth99). Most recently teaching at 
    Concordia University. 
  • *[Matt (Elvis) Husband](http://sites.google.com/site/emhusband)*. 
    Defended in 2010. Dissertation on stativity and aspectual composition. 
    Now an associate professor at the University of Oxford. 

%  • *[Gabriel Roisenberg Rodrigues](http://www.msu.edu/~rodri445)*. Currently working on scalar modifiers similar to _at least_ in Brazilian Portuguese. 

MA thesis committees I've chaired (excluding MAs by exam):

  • *Adam Gobeski*. Defended in 2009. Thesis on factor phrases. Went on to the 
    doctoral program.
  • *[Taehoon Hendrik Kim](http://kimhendrik.bol.ucla.edu)*. Defended 2016. 
    Thesis on concessivity and predicate focus in Korean. Now in the 
    linguistics Ph.D. program at UCLA. 
  • *Chris O’Brien*. Defended in 2012. Thesis on complement coercion in 
    aspectual verbs. Recently completed the linguistics Ph.D. program at MIT. 
  • *Ai Matsui (Kubota)*. Defended in 2008. Thesis on concessive 
    conditionals in Japanese. Went on to the doctoral program. Now Ai Kubota.
  • *Ben Johnson*. Co-chaired with [Alan Beretta](http://msu.edu/~beretta). 
    MA by exam in 2008. 
  • *John Douglas Mastin*. MA by exam in 2006. 

%  • *Kay Ann Schlang*. Worked on anaphoric demonstratives. 

I've also supervised a fair number of BA theses. The vast majority these students of them have gone on to sensible lives outside of linguistics, so I won't mention their sordid linguistics past here. Others, however, remained in the field:

  • *[Haley Farkas](http://sites.northwestern.edu/haleyfarkas)*. 2015. Went 
    on to the linguistics doctoral program at Northwestern, and ultimately 
    to the University of Southern California's. 
  • *[Taehoon Kim](http://kimhendrik.bol.ucla.edu)*. 2012. Went on to MSU 
    linguistics MA program. 
  • *[Karl DeVries](https://people.ucsc.edu/~kadevrie/)*. 2010. Currently in 
    the linguistics Ph.D. program at the University of California Santa Cruz. 
  • *Alex Clarke*. 2009. Went on to MSU linguistics MA program. 
  • *David Hunter*. 2007. Went on to linguistics MA program at the 
    University of Amsterdam. 
  • *[Peter (Peet/Pedro) Klecha](http://peterklecha.com/)*. 2007. 
    Went on to the Ph.D. program at the University of Chicago and visiting 
    positions at Ohio State, Swarthmore College, and the University of 
    Connecticut.

%Some other students I've worked with have webpages:
%You can find out more about Michigan State grad students in general on our grad student organization's [student](http://msulinguists.weebly.com/students.html) and [alumni](http://msulinguists.weebly.com/alumni.html) pages.

%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Marcin Morzycki &middot; Students

|DESCRIPTION|: List of some of Marcin Morzycki's students.

|KEYWORDS|: Marcin Morzycki, linguistics, teaching, students

%: ———————————————————————————————————————————————————————————————————————————

