|MONTH|: July
|YEAR|: 24


Students
————————

Doctoral students I've advised (in the US sense) and supervised (in the Canadian sense):

  • *[Starr Sandoval](https://blogs.ubc.ca/starrsandoval//)*. In progress.
    Working on on Ktunaxa, non-intersective modification, adjunct
    questions, expressive meaning and intensification.
  • *[Rose Underhill](https://linguistics.ubc.ca/profile/rose-underhill/)*.
    Defended in 2024. Dissertation on plurality in Ktunaxa, showing that the
    language structures its plurals around the notion of grouphood rather than
    mere multiplicity. This ultimately explains a correlation between plurality
    and animacy.
  • *Adam Gobeski*. Defended in 2019. Dissertation on factor phrases across 
    categories and the grammar of arithmetic. Now works in industry, but has been collaborating with me on a number of projects.
  • *[Cara Feldscher](https://msu.edu/~feldsch3)*. Defended in 2019. 
    Dissertation on means of providing additional information across 
    domains---for individuals, degrees, and events---including _also_, _still_, 
    and _again_. 
  • *[Ai Taniguchi][AiT]*. Defended in 2017. Dissertation: _The Formal 
    Pragmatics of Non-At-Issue Intensification in English and Japanese_. 
    Assistant professor at the University of Toronto Mississauga.
    % [Carleton University](http://carleton.ca/slals/people/taniguchi-ai) in 
    % Ottawa. 
    Not identical to Ai Kubota below. 
  • *[Curt Anderson](http://curtanderson.github.io)*. Defended in 2016. 
    Dissertation on attenuation, intensification, approximation, and slack 
    regulation. Held positions at the University of Toronto Scarborough and Universität Düsseldorf, and most recently at Gap International. 
  • *[Ai Kubota][old_ai]*. Defended in 2016. 
    Dissertation on evaluative adverbs and related issues in Japanese. 
    Went on to positions at Williams College and, currently, the University of Tokyo.
    Not identical to Ai Taniguchi above.     
  • *Olga Eremina*. 
    % *[Olga Eremina](https://www.hse.ru/en/org/persons/92284721)*. 
    Defended 
    in 2011. Dissertation on indefinites in Russian. 
    Went on to positions at Middlebury College, Dartmouth College, and the  National Research University Higher School of Economics in Moscow. 
    % Now at the National 
    % Research University Higher School of Economics in Moscow. Most recently 
    % teaching at Middlebury and Dartmouth Colleges. 
  • *Irina Agafonova*. Defended in 2010. Dissertation on conjunction in 
    Russian. Her work had a computational component, on which she was advised by
    [John Hale](https://linguistics.uga.edu/directory/people/john-hale). 
    Went on to a teaching position at Concordia University.
  • *[Matt Husband](http://sites.google.com/site/emhusband)*. 
    Defended in 2010. Dissertation on stativity and aspectual composition. 
    % Went on to positions at Brown University and now an 
    Associate professor at the University of Oxford. 

[AiT]: https://www.utm.utoronto.ca/language-studies/people/ai-taniguchi
[old_ai]: https://researchmap.jp/ai.kubota    

Doctoral students I advised for a number of years at my previous job:

%  • *[Gabriel Roisenberg Rodrigues](http://www.msu.edu/~rodri445)*. Currently working on scalar modifiers similar to _at least_ in Brazilian Portuguese. 
  • *[Josh Herrin](https://herrinjomsu.files.wordpress.com)*. Worked on (among 
    other things) on superlatives, _of_, and fronting of degree words inside 
    nominals (_the tallest of people_, _so tall (of) a person_). 
  • *[Yan Cong](http://linglang.msu.edu/people/graduate-students/yan-cong)*. 
    Worked on (among other things) subjectivity in Mandarin. 

MA thesis committees I've chaired (excluding MAs by exam):

  • *Adam Gobeski*. Defended in 2009. Thesis on factor phrases. Went on to the 
    doctoral program.
  • *[Taehoon Hendrik Kim](https://t-hendrik-kim.github.io)*. Defended 2016. 
    Thesis on concessivity and predicate focus in Korean. Now in the 
    linguistics Ph.D. program at UCLA. 
  • *Chris O’Brien*. Defended in 2012. Thesis on complement coercion in 
    aspectual verbs. Went on to the linguistics Ph.D. program at MIT. 
  • *Ai Matsui (Kubota)*. Defended in 2008. Thesis on concessive 
    conditionals in Japanese. Went on to the doctoral program. Now [Ai Kubota](#old_ai) above.
  % • *Ben Johnson*. Co-chaired with [Alan Beretta](http://msu.edu/~beretta). 
  %   MA by exam in 2008. 
  % • *John Douglas Mastin*. MA by exam in 2006. 

%  • *Kay Ann Schlang*. Worked on anaphoric demonstratives. 
%  • *Jared Galvan*. 

There's some BA theses I've advised. Most of these students have gone on to sensible lives outside of linguistics and I won't mention their sordid linguistics past here. Others, however, remained in the field for longer:

  • *[Natasha Chemey](https://www.nchemey.com)*. 2018. Went 
    on to the linguistics doctoral program at Rutgers. 
  • *[Haley Farkas](http://sites.northwestern.edu/haleyfarkas)*. 2015. Went 
    on to the linguistics doctoral program at Northwestern, and ultimately 
    to the University of Southern California's. 
  • *[Taehoon Kim](https://t-hendrik-kim.github.io)*. 2012. Went on to
    linguistics MA program at Michigan State University.
  • *[Karl DeVries](https://www.linkedin.com/in/karl-devries-a1480864)*. 2010. 
    Went on to the linguistics Ph.D. program at the University of California Santa Cruz. 
  • *Alex Clarke*. 2009. Went on to the linguistics MA 
    program at Michigan State University.
  • *David Hunter*. 2007. Went on to linguistics MA program at the 
    University of Amsterdam. 
  • *[Peter Klecha](http://www.peterklecha.com)*. 2007. Went on to the Ph.D.
    program at the University of Chicago and visiting professor positions at
    Ohio State, Swarthmore College, and the University of Connecticut.

%Some other students I've worked with have webpages:
%You can find out more about Michigan State grad students in general on our grad student organization's [student](http://msulinguists.weebly.com/students.html) and [alumni](http://msulinguists.weebly.com/alumni.html) pages.

%:————————————————————————————————————————————————————————————————————————————

|TITLE|: Morzycki &middot; Students
|DESCRIPTION|: List of some of Marcin Morzycki's students.
|KEYWORDS|: Marcin Morzycki, linguistics, teaching, students

|ROOT|: ../
|FILEURL|: http://morzycki.github.io/students

%: ———————————————————————————————————————————————————————————————————————————

