
## Creaky voice examples

Hausa <span class="note">(Chadic, >25 million speakers, West Africa)</span> 

[[jaː]][he] 'he'  
[[j̰aː]][daughter] 'daughter'

Kambaata <span class="note">(Cushitic, half million speakers, Ethiopia)</span>

[[worano]][insert] 'insert'  
[[gor̰ano]][green] 'it will be green'

%[[adala]][herb] (an herb)  
%[[ga̰la]][shard] 'shard'
  %: the 'herb' thing is clearly the wrong form, but it's Ladefoged's mistake,
  %: not mine

<embed src="../phonation/hausa/he.aiff" name="he" autostart="false" hidden="true" />
[he]: javascript:sound('he')

<embed src="../phonation/hausa/daughter.aiff" name="daughter" autostart="false" hidden="true" />
[daughter]: javascript:sound('daughter')

<embed src="../phonation/kambaata/insert.wav" name="insert" autostart="false" hidden="true" />
[insert]: javascript:sound('insert')

<embed src="../phonation/kambaata/green.wav" name="green" autostart="false" hidden="true" />
[green]: javascript:sound('green')


<embed src="../phonation/kambaata/herb.wav" name="herb" autostart="false" hidden="true" />
[herb]: javascript:sound('herb')

<embed src="../phonation/kambaata/shard.wav" name="shard" autostart="false" hidden="true" />
[shard]: javascript:sound('shard')


