
## Breathy voice in Gujarati

[[bar]][bar] 'twelve'  
[[ba̤r]][bar_m] 'outside'

[[mɛl]][mel] 'dirt'  
[[mɛ̤l]][mel_m] 'palace'
  %: looks like nothing's there, but it's just that TM has trouble with symbol

[[pɔr]][por] 'last year'  
[[pɔ̤r]][por_m] 'dawn'

[[kan]][kan] 'Krishna'  
[[ka̤n]][kan_m] 'ear'

(note): Indo-Aryan branch of Indo-European; 45 million speakers; western India

<embed src="../phonation/gujarati/ear.aiff" name="kan" autostart="false" hidden="true" />
[kan]: javascript:sound('kan')

<embed src="../phonation/gujarati/krishna.aiff" name="kan_m" autostart="false" hidden="true" />
[kan_m]: javascript:sound('kan_m')

<embed src="../phonation/gujarati/last year.aiff" name="por" autostart="false" hidden="true" />
[por]: javascript:sound('por')

<embed src="../phonation/gujarati/dawn.aiff" name="por_m" autostart="false" hidden="true" />
[por_m]: javascript:sound('por_m')

<embed src="../phonation/gujarati/dirt.aiff" name="mel" autostart="false" hidden="true" />
[mel]: javascript:sound('mel')

<embed src="../phonation/gujarati/palace.aiff" name="mel_m" autostart="false" hidden="true" />
[mel_m]: javascript:sound('mel_m')

<embed src="../phonation/gujarati/twelve.aiff" name="bar" autostart="false" hidden="true" />
[bar]: javascript:sound('bar')

<embed src="../phonation/gujarati/outside.aiff" name="bar_m" autostart="false" hidden="true" />
[bar_m]: javascript:sound('bar_m')


%
%<embed src="../clicks/xoo/dental.aiff" name="dental" autostart="false" hidden="true" />
%[dental]: javascript:sound('dental')
%
%<embed src="../clicks/xoo/alveolar.aiff" name="alveolar" autostart="false" hidden="true" />
%[alveolar]: javascript:sound('alveolar')
%
%<embed src="../clicks/xoo/palatal.aiff" name="palatal" autostart="false" hidden="true" />
%[palatal]: javascript:sound('palatal')
%
%<embed src="../clicks/xoo/lateral.aiff" name="lateral" autostart="false" hidden="true" />
%[lateral]: javascript:sound('lateral')
