
## Cast of characters

• [labial][labial] (more precisely, bilabial): 

  (display): [ʘ]

• [dental][dental]:

  (display): [ǀ]

• [alveolar][alveolar] (more precisely, postalveolar or alveolopalatal):

  (display): [!]

• [palatal][palatal] (more precisely, palatoalveolar):

  (display): [ǂ]

• [alveolar lateral][lateral]:

  (display): [ǁ]

<embed src="../clicks/labial.aiff" name="labial" autostart="false" hidden="true" />
[labial]: javascript:sound('labial')

<embed src="../clicks/dental.aiff" name="dental" autostart="false" hidden="true" />
[dental]: javascript:sound('dental')

<embed src="../clicks/alveolar.aiff" name="alveolar" autostart="false" hidden="true" />
[alveolar]: javascript:sound('alveolar')

<embed src="../clicks/palatal.aiff" name="palatal" autostart="false" hidden="true" />
[palatal]: javascript:sound('palatal')

<embed src="../clicks/lateral.aiff" name="lateral" autostart="false" hidden="true" />
[lateral]: javascript:sound('lateral')

