
## Creaky and breathy voice in Mazatec

[[tʰæ]][seed] 'seed'  
[[ndæ̰]][buttocks] 'buttocks'  
[[ndæ̤]][horse] 'horse'
  %: CAREFUL!: The above two lines are invisible in TM, but present.

(note): Oto-Manguean; 100,000 speakers; Mexico

<embed src="../phonation/mazatec/seed.aiff" name="seed" autostart="false" hidden="true" />
[seed]: javascript:sound('seed')

<embed src="../phonation/mazatec/buttocks.aiff" name="buttocks" autostart="false" hidden="true" />
[buttocks]: javascript:sound('buttocks')

<embed src="../phonation/mazatec/horse.aiff" name="horse" autostart="false" hidden="true" />
[horse]: javascript:sound('horse')


