
## Creaky voice in Mpi

Actually tense voice, which resembles creaky. Tone not indicated.

%: blood is low level, color is mid level
[[si]][blood] 'blood'  
[[sḭ]][seven] 'seven'  
[[si]][color] a color  
[[sḭ]][classifier] classifier
  %: CAREFUL!: the apparently empty lines here are just invisible due to TM

(note): Sino-Tibetan, 900 speakers, Thailand


<embed src="../phonation/mpi/blood.aiff" name="blood" autostart="false" hidden="true" />
[blood]: javascript:sound('blood')

<embed src="../phonation/mpi/seven.aiff" name="seven" autostart="false" hidden="true" />
[seven]: javascript:sound('seven')

<embed src="../phonation/mpi/color.aiff" name="color" autostart="false" hidden="true" />
[color]: javascript:sound('color')

<embed src="../phonation/mpi/classifier.aiff" name="classifier" autostart="false" hidden="true" />
[classifier]: javascript:sound('classifier')

