
## Breathy voice in Nawari

[[maa]][garland] 'garland'  
[[m̤aa]][unwilling] 'to be unwilling'

[[naa]][melts] 'it melts'  
[[n̤aa]][knead] 'knead'

(note): Tibetu-Burman; 500,000 speakers; Nepal

<embed src="../phonation/nawari/garland.aiff" name="garland" autostart="false" hidden="true" />
[garland]: javascript:sound('garland')

<embed src="../phonation/nawari/unwilling.aiff" name="unwilling" autostart="false" hidden="true" />
[unwilling]: javascript:sound('unwilling')

<embed src="../phonation/nawari/melts.aiff" name="melts" autostart="false" hidden="true" />
[melts]: javascript:sound('melts')

<embed src="../phonation/nawari/knead.aiff" name="knead" autostart="false" hidden="true" />
[knead]: javascript:sound('knead')

