
## Velaric airstream mechanism

elements of an alveolar click:

• load
	• closure as for a velar stop (start a \[k\])
	• alveolar closure (add a \[t\])
	• tongue dips, creating low-pressure air pocket
• fire!
  • alveolar closure released
  • velar closure released

[X-ray](../clicks/x-ray.mov) \(palatal?\)

with vowels: [\[a!a\]][alveolar]
[alveolar]: javascript:sound('alveolar')

<embed src="../clicks/alveolar.aiff" name="alveolar" autostart="false" hidden="true" />

real-world examples of clicks:

• [!Xóõ](Xoo.html)
• [Zulu](Zulu.html)
