
## Clicks in \!Xóõ

• labial: [[ʘʔôo]][labial] 'get stuck'
• dental: [[kǀʔâa]][dental] 'die'
• alveolar: [[k!ʔáã]][alveolar] 'be seated'
• palatal: [[kǂʔaa]][palatal] 'shoot you'
• alveolar lateral: [[kǁʔàa]][lateral] 'not to be'

(note): Khoisan; 4,000 speakers; southern Africa

<embed src="../clicks/xoo/labial.aiff" name="labial" autostart="false" hidden="true" />
[labial]: javascript:sound('labial')

<embed src="../clicks/xoo/dental.aiff" name="dental" autostart="false" hidden="true" />
[dental]: javascript:sound('dental')

<embed src="../clicks/xoo/alveolar.aiff" name="alveolar" autostart="false" hidden="true" />
[alveolar]: javascript:sound('alveolar')

<embed src="../clicks/xoo/palatal.aiff" name="palatal" autostart="false" hidden="true" />
[palatal]: javascript:sound('palatal')

<embed src="../clicks/xoo/lateral.aiff" name="lateral" autostart="false" hidden="true" />
[lateral]: javascript:sound('lateral')
