
## Clicks in Zulu

Voiceless:

• dental: [[kǀáːgà]][dental] 'to whitewash'
• alveolar: [[k!àːká]][alveolar] 'to undo'
• alveolar lateral: [[kǁáːgà]][lateral] 'to put into a fix' (wtf?)

Voiced ([ɓ] is a voiced bilabial implosive):

• dental: [[gǀòːɓá]][v_dental] 'to grease'
• alveolar: [[g!òːɓá]][v_alveolar] 'to milk'
• alveolar lateral: [[gǁòːɓá]][v_lateral] 'to beat'

Voiced nasal:

• dental: [[ìsìːŋǀé]][n_dental] (a kind of spear)
• alveolar: [[ìsìːŋ!é]][n_alveolar] 'rump'
• alveolar lateral: [[ìsìːŋǁéːlè]][n_lateral] 'left hand'

(note): Bantu; 10 million speakers; South Africa

<embed src="../clicks/zulu/dental.aiff" name="dental" autostart="false" hidden="true" />
[dental]: javascript:sound('dental')

<embed src="../clicks/zulu/alveolar.aiff" name="alveolar" autostart="false" hidden="true" />
[alveolar]: javascript:sound('alveolar')

<embed src="../clicks/zulu/lateral.aiff" name="lateral" autostart="false" hidden="true" />
[lateral]: javascript:sound('lateral')

<embed src="../clicks/zulu/v_dental.aiff" name="v_dental" autostart="false" hidden="true" />
[v_dental]: javascript:sound('v_dental')

<embed src="../clicks/zulu/v_alveolar.aiff" name="v_alveolar" autostart="false" hidden="true" />
[v_alveolar]: javascript:sound('v_alveolar')

<embed src="../clicks/zulu/v_lateral.aiff" name="v_lateral" autostart="false" hidden="true" />
[v_lateral]: javascript:sound('v_lateral')

<embed src="../clicks/zulu/n_dental.aiff" name="n_dental" autostart="false" hidden="true" />
[n_dental]: javascript:sound('n_dental')

<embed src="../clicks/zulu/n_alveolar.aiff" name="n_alveolar" autostart="false" hidden="true" />
[n_alveolar]: javascript:sound('n_alveolar')

<embed src="../clicks/zulu/n_lateral.aiff" name="n_lateral" autostart="false" hidden="true" />
[n_lateral]: javascript:sound('n_lateral')

