%: NB: the date of this is set explicitly below, so will need manual updating


Clicks and phonation types
==========================

Everything below is from the [publicly available materials](http://hctv.humnet.ucla.edu/departments/linguistics/VowelsandConsonants) accompanying Peter Ladefoged's books _A Course in Phonetics_ and _Vowels and Consonants_---you can find all this and lots, lots more there. 
%It's possible that some of the IPA below won't render correctly in your browser. 
The phonetics stuff from earlier in the semester is [here](index.html).

Clicks:

• the [airstream mechanism](variation/velaric_airstream.html) behind clicks
• voiceless clicks in [!Xóõ](variation/Xoo.html)
• voiceless, voiced, and nasal clicks in [Zulu](variation/Zulu.html)

Creaky voice/laryngealization:

• vowels in [Mpi](variation/mpi.html)
• consonants in [Hausa and Kambaata](variation/creaky.html)

Breathy voice:

• vowels in [Gujarati](variation/Gujarati.html)
• nasals in [Nawari](variation/nawari.html)
• breathy and creaky vowels in a single language in [Mazatec](variation/mazatec.html) 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

|DESCRIPTION|: Examples of clicks and phonation types from Ladefoged.

|KEYWORDS|: clicks, phonation types, breathy, creaky, murmured, laryngealized, voicing, phonetics, linguistics, 401, Morzycki

|MONTH|: November
|YEAR|: 10

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
