%: NB: the date of this is set explicitly below, so will need manual updating


Phonetics stuff
===============

### X-ray films

%: NB: This looks weird if placed above the header, as would seem more
%:     logical.
%<div class="picture">
%  <img src="../pix/japanese_crap.jpg" alt="I'm a crap"/><br />
% <em>A sign in Japan unintentionally revealing that voicing matters. (The 
%   image is from <a href="http://engrish.com">engrish.com</a>.)</em>
%</div>
%  <em>A sign in Japan, unintentionally revealing that
%	voicing is contrastive in English. (The image is from <a
%	href="http://engrish.com">engrish.com</a>.)</em>

These are x-ray films of vocal tracts making various odd declarations, 
% (Why all Canadians? Unclear. At least one of these was recorded in Sweden.)
all from the [X-Ray Database page][x_ray_database] at the [Queen's University Speech Perception and Production Laboratory][queens_lab]. (These are links to the QuickTime versions; other formats are available on the original website.)

[x_ray_database]: http://psyc.queensu.ca/~munhallk/05_database.htm
[queens_lab]: http://psyc.queensu.ca/~munhallk

• An anonymous 38-year-old male vocal tract asks the age-old question ['Why 
  did Ken set the soggy net on top of his deck?'](soggynet.mov). (There does 
  not appear to be an x-ray film of Ken's vocal tract explaining his 
  soggy-net-placement decisions, unfortunately.) 
• The anonymous 38-year-old male vocal tract says a variety of other things, 
  too. You can watch [the full recording](fullxray.mov). 
• An anonymous 26-year-old male vocal tract says: ['It's ten below 
  outside'](10below.mov). (Meteorologically shocking revelation: this was 
  recorded in Quebec.) 
• An anonymous female vocal tract of unknown age announces in Canadian 
  French that ['Le boulanger but onze bières'](leboulanger.mov) ('The baker 
  drank eleven beers'). 


### Vocal folds

This is what vibrating vocal folds look like (in slow motion):

<img src="vocalfolds_horiz.gif" alt="[Vocal folds in action]" />
%<img src="vocalfolds.gif" alt="[Vocal folds in action]" />

This is from the [UCLA Phonetics Lab][ucla_lab] [demos and illustrations][ucla_demos] page.

[ucla_lab]: http://www.humnet.ucla.edu/humnet/linguistics/faciliti/uclaplab.html
[ucla_demos]: http://www.humnet.ucla.edu/humnet/linguistics/faciliti/demos/demos.html


### Elaborate multimedia thing

% Multimedia <span class="strikeout">Toy</span> Study Tool

You might want to play with [this multimedia dingus][multimedia_toy] about the phonetics of English from the University of Iowa. There are IPA symbols bouncing around, animations of various sounds being articulated, and videos of a very earnest-looking person---whose insides you are not forced to look at---making those sounds.

A warning, though: The terminology it uses varies slightly from what we've been using in class. The main difference is that all places of articulation in which the tongue 
is the active articulator (the chunk of meat that's moving)
% is the active articulator
are prefixed with <em>lingua-</em>. I don't know why this site in particular has this apparent tongue fixation, but this illustrates a more general fact: there is variation in phonetic terminology. Even apart from that, the same sound might be characterized in different ways depending on what is relevant in a particular context. For example, one might call attention to the fact that English \[t\] is made with the blade of the tongue by using the term 'laminal', and describing this sound as a 'laminal voiceless alveolar stop'.

(There is also a [Spanish version][spanish_toy] of this site. You probably shouldn't look at it, though, until you're relatively confident of your grasp of the basics of the phonetics of English.)

[multimedia_toy]: http://www.uiowa.edu/~acadtech/phonetics/english/frameset.html
[spanish_toy]: http://www.uiowa.edu/~acadtech/phonetics/spanish/frameset.html


<!-- <h2>Sounds of the Worlds Languages</h2>

Examples of various sounds being made by native speakers of languages that have them are available here. -->


### Full IPA chart

Here is the [chart][ipa_chart] that reflects all the standard symbols in the IPA. Definitely don't look at this unless you have a handle on what we're doing in class. This version is actually clickable, so you can hear examples of various sounds.
<!-- If you do, though, you might want to consider ways in which what we're doing departs from the system here, and why it might make sense to do so. -->

[ipa_chart]: http://web.uvic.ca/ling/resources/ipa/charts/IPAlab/IPAlab.htm

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

|TITLE|: Phonetics Stuff

|DESCRIPTION|: Some phonetics stuff.

|KEYWORDS|: phonetics, linguistics, demonstrations, disturbing, alarming, blech

|MONTH|: February
|YEAR|: 10

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
